modLoader="javafml"
loaderVersion="${forge_loader_version}"
license="MIT"
[[mods]]
modId="cloud_tweaks"
version="${version}"
displayName="Cloud Tweaks"
description="Customize your clouds!"
authors="not_thefirst"
credits="Tixork for burning down my house!"
logoFile="assets/cloud_tweaks/icon.png"

[[dependencies.cloud_tweaks]]
    modId="forge"
    mandatory=true
    versionRange="${forge_loader_version}"
    ordering="NONE"
    side="CLIENT"

[[dependencies.cloud_tweaks]]
    modId="cloth_config"
    versionRange="[11,)"
    mandatory=false
    ordering="AFTER"
    side="CLIENT"

[[dependencies.cloud_tweaks]]
    modId="minecraft"
    versionRange="[1.21.9, 1.21.11]"
    mandatory=true
    ordering="NONE"
    side="CLIENT"