modLoader="javafml"
loaderVersion="[1,)"
license="MIT"
[[mods]]
modId="cloud_tweaks"
version="0.1.1"
displayName="Cloud Tweaks"
description="Customize your clouds!"
authors="not_thefirst"
credits="Tixork for burning down my house!"
logoFile="assets/cloud_tweaks/icon.png"

[[dependencies.cloud_tweaks]]
    modId = "neoforge"
    type = "required"
    versionRange = "[21,)"
    ordering = "NONE"
    side = "CLIENT"

[[dependencies.cloud_tweaks]]
    modId="cloth_config"
    versionRange="[1,)"
    type = "optional"
    ordering="AFTER"
    side="CLIENT"

[[dependencies.cloud_tweaks]]
    modId="minecraft"
    versionRange="[1.21.6, 1.21.10]"
    type = "required"
    ordering="NONE"
    side="CLIENT"

[[mixins]]
config = "cloud_tweaks.mixins.json"